In [3]:
import numpy as np

In [20]:
a = [1, 2, 3, True, 'hello']
b = np.array([1, 2, 3])

In [7]:
type(a)

list

In [22]:
numbers = [3, 6, 8, 5]

In [23]:
numbers

[3, 6, 8, 5]

In [28]:
# double_numbers = [2 * num for num in numbers]
double_numbers = []

for num in numbers:
    double_numbers.append(2*num)
# [6, 12, 16, 10]

In [29]:
double_numbers

[6, 12, 16, 10]

In [30]:
numbers = np.array([3, 6, 8, 5])

In [31]:
numbers * 2

array([ 6, 12, 16, 10])

In [32]:
numbers + 2

array([ 5,  8, 10,  7])

In [33]:
numbers - 5

array([-2,  1,  3,  0])

In [43]:
for i in np.arange(2, 3, 0.2):
    print(i)

2.0
2.2
2.4000000000000004
2.6000000000000005
2.8000000000000007


In [58]:
data = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(data, dtype='int16')

In [53]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [54]:
arr[1][0]

np.int16(5)

In [55]:
arr.shape

(2, 4)

In [59]:
arr.ndim

2

In [60]:
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int16)

In [61]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int16)

In [63]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
a = np.zeros((3, 6, 2))

In [71]:
a.ndim

3

In [ ]:
np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [73]:
np.array([
    [
        [1, 2], [3, 4]
    ], 
    [
        [4, 3], [5, 6]
    ]
]).shape

(2, 2, 2)

In [76]:
np.ones((3, 2, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [85]:
np.empty((2, 3, 2, 4, 1, 2))

array([[[[[[2.12199584e-314, 0.00000000e+000]],

          [[9.88131292e-324, 4.24399163e-314]],

          [[0.00000000e+000, 9.88131292e-324]],

          [[5.33590898e-322, 0.00000000e+000]]],


         [[[9.88131292e-324, 2.12199584e-314]],

          [[0.00000000e+000, 9.88131292e-324]],

          [[6.17582057e-322, 0.00000000e+000]],

          [[9.88131292e-324, 4.94065646e-324]]]],



        [[[[0.00000000e+000, 9.88131292e-324]],

          [[2.12199584e-314, 0.00000000e+000]],

          [[1.48219694e-323, 6.36598742e-314]],

          [[0.00000000e+000, 1.48219694e-323]]],


         [[[4.24399164e-314, 0.00000000e+000]],

          [[1.48219694e-323, 6.36598743e-314]],

          [[0.00000000e+000, 1.48219694e-323]],

          [[2.12199585e-314, 0.00000000e+000]]]],



        [[[[1.48219694e-323, 4.94065646e-324]],

          [[0.00000000e+000, 1.48219694e-323]],

          [[2.12199584e-314, 0.00000000e+000]],

          [[1.97626258e-323, 8.48798321e-314]]],


      

In [95]:
arr1 = np.array([1, 2, 3], dtype='int16')

In [92]:
arr1.dtype

dtype('int16')

In [96]:
arr1 = np.array([1, 2, 3], dtype=np.int16)


In [100]:
arr1 = np.array([[2, 1], [5, 2]])
arr2 = np.array([[4, 3], [7, 2]])

In [103]:
arr1 * arr2

array([[ 8,  3],
       [35,  4]])

In [104]:
arr1 @ arr2

array([[15,  8],
       [34, 19]])

In [106]:
arr1.dot(arr2)

array([[15,  8],
       [34, 19]])

In [107]:
a = [1, 4, 5, 8, 4, 3]
a == 4

False

In [108]:
a = np.array([1, 4, 5, 8, 4, 3])
a == 4

array([False,  True, False, False,  True, False])

In [110]:
np.where(
    a >= 5,
    a,
    0
)

array([0, 0, 5, 8, 0, 0])

In [112]:
arr = np.array(
    [
        [1, 2], 
        [3, 4]
    ]
)
print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1)) 

10
[4 6]
[3 7]
